runmode: dev
gormlog: true
addr: :6662
url: http://127.0.0.1:6662
name: apiserver
allow_origin: http://xxxx.xxx.com # vue框架授权来源
max_ping_count: 10
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  addr: :6663
  cert: conf/server.crt
  key: conf/server.key
db:
  name: db_apiserver
  addr: 10.50.226.110:3306
  username: micro
  password: micro
docker_db:
  name: db_apiserver
  addr: 10.50.226.110:3306
  username: micro
  password: micro
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1024
  log_backup_count: 7
